apiVersion: v1                                                                                                         
baseDomain: lab-cluster.local                                                                                          
cpuPartitioningMode: AllNodes                                                                                          
compute:                                                                                                               
- architecture: amd64                                                                                                  
  hyperthreading: Enabled                                                                                              
  name: worker                                                                                                         
  platform: {}                                                                                                         
  replicas: 0                                                                                                          
controlPlane: 
  architecture: amd64      
  hyperthreading: Enabled
  name: master
  platform: {}                                       
  replicas: 1                                           
metadata: 
  name: ocp4  
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 192.168.46.0/24
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
pullSecret: ''
sshKey: ''
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  MIID9DCCAtygAwIBAgIUTna2+s1YPd/VitCbyfUyS7pnVHowDQYJKoZIhvcNAQEL
  BQAwdDELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAlZBMREwDwYDVQQHDAhOZXcgWW9y
  azENMAsGA1UECgwEUXVheTERMA8GA1UECwwIRGl2aXNpb24xIzAhBgNVBAMMGnJl
  F0RSndEY1sI=
  -----END CERTIFICATE-----
imageDigestSources:
- mirrors:
  - registry.lab-cluster.local:8443/openshift/release
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
- mirrors:
  - registry.lab-cluster.local:8443/openshift/release-images
  source: quay.io/openshift-release-dev/ocp-release
---
apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: sno-cluster
rendezvousIP: 192.168.46.11
hosts:
  - hostname: master-0
    interfaces:
      - name: eth0
        macAddress: 00:50:56:8e:ee:25 
    networkConfig:
      interfaces:
        - name: eth0
          type: ethernet
          state: up
          mac-address: 00:50:56:8e:ee:25
          ipv4:
            enabled: true
            address:
              - ip: 192.168.46.11
                prefix-length: 24
            dhcp: false
      dns-resolver:
        config:
          server:
            - 192.168.46.10
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.46.1
            next-hop-interface: eth0
            table-id: 254

