apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - openshift-cnv-hyperconverged.yaml
  - openshift-cnv-namespace.yaml
  - openshift-cnv-operatorgroup.yaml
  - openshift-cnv-subscription.yaml