apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd-instance.yaml
  - gitops-cluster-admin-binding.yaml
  - gitops-ns.yaml
  - gitops-operatorgroup.yaml
  - gitops-subscription.yaml
