apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - compliance_namespace.yaml
  - compliance_operatorgroups.yaml
  - scansettingbinding.yaml
  - compliance_subscription.yaml